[package]
name = "pymemprofile_preload"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@pythonspeed.com>"]
edition = "2018"

[dependencies]
redhook = "1.0"
libc = "0.2"
libloading = "0.5"

[lib]
name = "pymemprofile_preload"
crate_type = ["dylib"]