[package]
name = "pymemprofile"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@pythonspeed.com>"]

[dependencies]
redhook = "1.0"
libc = "0.2"

[lib]
name = "pymemprofile"
crate_type = ["dylib"]