[package]
name = "pymemprofile_api"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@pythonspeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "14.2.0"
libc = "0.2"
itertools = "0.8.2"
lazy_static = "1.4.0"

[dependencies.inferno]
version = "0.9.4"
default-features = false

[dev-dependencies]
proptest = "0.9.5"

[lib]
name = "pymemprofile_api"
crate_type = ["cdylib"]