[package]
name = "pymemprofile_api"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@itamarst.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procinfo = "0.4"
page_size = "0.4"
im = "14.1.0"
libc = "0.2"
itertools = "0.8.2"
crossbeam = "0.7.3"
lazy_static = "1.4.0"

[lib]
name = "pymemprofile_api"
crate_type = ["cdylib"]